export const questions2 = {
  '1': 'Purpose and concept of a module/module pattern',
  // The module pattern allows you to split up your code into smaller, reusable pieces
  '2': 'Types of modules (AMD, ES6, CommonJS, UMD)',
  // CommonJS UMD AMD ES6 Modules Bundlers like Browserify, Webpack, Rollup
  '3': 'Syntax and common features (export default, named exports, exports as).',
  '4': 'Dynamic imports.',
  '5': 'Callbacks and IIFE.',
  '6': 'Limitations of callbacks (e.g., callback hell).',
  '7': 'Function currying and partial functions.',
  '8': 'new keyword functionality',
  '9': 'Constructor functions and their properties',
  '10': 'Public, private, and static members in OOP.',
  '11': 'Class declaration and syntax.',
  '12': 'Differences between class declarations and constructor functions.',
  '13': 'Usage of super().',
  '14': 'Properties like __proto__ and prototype',
  '15': 'Using [Object.create] to define prototypes explicitly.',
  '16': 'Set/Map and WeakSet/WeakMap.',
  '17': 'Error handling techniques including try..catch.',
  '18': 'Understanding and implementing custom errors.',
  '19': 'Promises, async/await, and the event loop.',
  '20': 'Garbage collection basics.',
  '21':'Understanding browsers location and history API.',
  '22':'User agent parsing and platform/browser detection.',
  '23':'Parsing, reflow, repaint, and the critical rendering path.',
  '24':'Using Fetch and understanding XMLHTTPRequest.',
  '25':'Differences between setTimeout and requestAnimationFrame.',
  '26':'Writing efficient TypeScript using basic types, enums, interfaces, and generics,basic types,enums, type interface, differences between them,using interfaces with optional properties, read-only properties,function types,utitily types (optional),typeguards (optional),creating custom types,generic types (concept)',
  '27':'Understanding the module system in ES6 and TypeScript.',
  '28':'Familiarity with Creational, Structural, and Behavioral Design Patterns.',
  '29':'SOLID principles and design patterns in project contexts',
  '30':'Agile, Scrum, Kanban, and Waterfall methodologies.',
  '31':'Project estimation techniques.',
  '32':'Understanding different types of testing (Integration, E2E, Performance).',
  '33':'Test Pyramid.',
  '34':'Test-driven development (TDD) and behavior-driven development (BDD).',
  '35': '',
  '36': ''
}